version: '3.8'

services:
  spa-booking:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ../backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - spa-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - spa-network
    volumes:
      - redis-data:/data

networks:
  spa-network:
    driver: bridge

volumes:
  redis-data: